### PR TITLE
fix: `btoa` not supporting Unicode (closes #2)

### LINKED ISSUE #2: Validated fields not supporting Unicode?
When using CJK characters in `fields` with `x-www-form-urlencoded`, a 500 Internal Server Error occurs.

I didn't put `slug` in `options`, so it appears it isn't validated, allowing me to use CJK characters there.

image

image

### PR DESCRIPTION
**Pull request by OverflowCat**
After some console logs, I found that the bug is caused by `window.btoa` not supporting UTF-8, as explained in [this StackOverflow answer](https://stackoverflow.com/a/30106551).

pre

post

Also I added some docs :)

### CODE REVIEW

**Comment by zanechua** [comment]
@OverflowCat thanks for the PR.

Actually I already added a new library to support UTF8. I would gladly merge your docs update though.

If you're okay with that, could you rebase? 😊

**Comment by OverflowCat** [comment]
I've added several error messages based on my debugging experience, which can help in the setup process. I've tested the changes by deployment.

Also, the `deploy` script appears to unusable due to [pnpm's `deploy` command](https://github.com/pnpm/pnpm/issues/5163). What about changing a name?

**Comment by zanechua** [comment]
Didn't know about that ticket, yeah I think makes sense to change it.

I'll merge this first.

**Comment by zanechua** [comment]
Oh and I forgot to say:

Thank you for the PR :)

@OverflowCat

**Pull request merged**
